//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PianoWPFClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PianoWPFClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream DO_sostenido_1 {
            get {
                return ResourceManager.GetStream("DO_sostenido_1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream DO_sostenido_2 {
            get {
                return ResourceManager.GetStream("DO_sostenido_2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream DO1 {
            get {
                return ResourceManager.GetStream("DO1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream DO2 {
            get {
                return ResourceManager.GetStream("DO2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream FA_sostenido_1 {
            get {
                return ResourceManager.GetStream("FA_sostenido_1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream FA_sostenido_2 {
            get {
                return ResourceManager.GetStream("FA_sostenido_2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream FA1 {
            get {
                return ResourceManager.GetStream("FA1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream FA2 {
            get {
                return ResourceManager.GetStream("FA2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream LA_sostenido_1 {
            get {
                return ResourceManager.GetStream("LA_sostenido_1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream LA_sostenido_2 {
            get {
                return ResourceManager.GetStream("LA_sostenido_2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream LA1 {
            get {
                return ResourceManager.GetStream("LA1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream LA2 {
            get {
                return ResourceManager.GetStream("LA2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream MI_sostenido_1 {
            get {
                return ResourceManager.GetStream("MI_sostenido_1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream MI_sostenido_2 {
            get {
                return ResourceManager.GetStream("MI_sostenido_2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream MI1 {
            get {
                return ResourceManager.GetStream("MI1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream MI2 {
            get {
                return ResourceManager.GetStream("MI2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream RE_sostenido_1 {
            get {
                return ResourceManager.GetStream("RE_sostenido_1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream RE_sostenido_2 {
            get {
                return ResourceManager.GetStream("RE_sostenido_2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream RE1 {
            get {
                return ResourceManager.GetStream("RE1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream RE2 {
            get {
                return ResourceManager.GetStream("RE2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream SI_sostenido_1 {
            get {
                return ResourceManager.GetStream("SI_sostenido_1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream SI_sostenido_2 {
            get {
                return ResourceManager.GetStream("SI_sostenido_2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream SI1 {
            get {
                return ResourceManager.GetStream("SI1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream SI2 {
            get {
                return ResourceManager.GetStream("SI2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream SOL_sostenido_1 {
            get {
                return ResourceManager.GetStream("SOL_sostenido_1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream SOL_sostenido_2 {
            get {
                return ResourceManager.GetStream("SOL_sostenido_2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream SOL1 {
            get {
                return ResourceManager.GetStream("SOL1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream SOL2 {
            get {
                return ResourceManager.GetStream("SOL2", resourceCulture);
            }
        }
    }
}
